language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
      env: SPARK_VERSION=1.2
    - python: 2.7
      env: SPARK_VERSION=1.3
    - python: 3.3
    - python: 3.4

addons:
  postgresql: "9.3"

services:
    - mongodb
    - postgres
    - mysql

install:
  # install mysql odbc drivers

  - sudo apt-get install libmyodbc
  - echo '[mysql]' >> /etc/odbcinst.ini
  - echo 'Description=MySQL Driver' >> /etc/odbcinst.ini
  - echo 'Driver=/usr/lib/odbc/libmyodbc.so' >> /etc/odbcinst.ini

  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n odo-test python=$TRAVIS_PYTHON_VERSION pytest numpy pandas sqlalchemy h5py pip cython bcolz coverage networkx toolz multipledispatch pytables dynd-python pymongo paramiko boto dask
  - source activate odo-test

  # Install various deps
  - pip install pymysql psycopg2 sas7bdat

  # Install DataShape
  - pip install --upgrade git+http://github.com/ContinuumIO/datashape

  # redshift sqlalchemy dialect
  - pip install --upgrade git+git://github.com/cpcloud/redshift_sqlalchemy

  # install pyspark
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then conda install spark=$SPARK_VERSION -c blaze -c https://conda.binstar.org/blaze/channel/dev; fi

  # Install Bokeh
  - if [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; then conda install bokeh; fi

  # For bcolz
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda install unittest2; fi

# Before_script section stolen from fabric
# See license https://github.com/fabric/fabric/blob/master/LICENSE
before_script:
 # Allow us to SSH passwordless to localhost
 - ssh-keygen -f ~/.ssh/id_rsa -N ""
 - cp ~/.ssh/{id_rsa.pub,authorized_keys}
 # Creation of an SSH agent for testing forwarding
 - eval $(ssh-agent)
 - ssh-add
 - mysql -e "create database if not exists test;" -u root

script:
    - py.test --doctest-modules odo

notifications:
  email: false
