sudo: False

language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: PANDAS_VERSION=0.19.0
    - python: 3.4
      env: PANDAS_VERSION=0.19.0
    - python: 3.5
      env: PANDAS_VERSION=0.19.0
    - python: 2.7
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"
    - python: 3.4
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"
    - python: 3.5
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"
  allow_failures:
    - python: 2.7
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"
    - python: 3.4
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"
    - python: 3.5
      env: PANDAS_VERSION="git+https://github.com/pydata/pandas"

addons:
  postgresql: "9.3"

services:
    - mongodb
    - mysql

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  # Use conda **ONLY** for numpy and pandas, this speeds up the builds a
  # lot. Use the normal pip install for the rest.
  - conda create -n odo python=$TRAVIS_PYTHON_VERSION pandas=$PANDAS_VERSION numpy=1.11.2
  - source activate odo
  # update setuptools and pip
  - conda update setuptools pip

  # install the frozen ci dependencies
  - pip install -e .[ci]

  # datashape
  - pip install git+git://github.com/blaze/datashape.git

  # redshift sqlalchemy dialect
  - pip install --upgrade git+git://github.com/graingert/redshift_sqlalchemy

# Before_script section stolen from fabric
# See license https://github.com/fabric/fabric/blob/master/LICENSE
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add
  - "mongo admin --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true});'"
  - mysql -e "create database if not exists test;" -u root
  - psql -c "create database test;" -U postgres
  - sleep 15

script:
  - conda list
  - py.test -v --doctest-modules --doctest-ignore-import-errors -rs odo

notifications:
  email: false
